class LineTypes:
    def __init__(self):
        self.assist = {"r_ohm_per_km": 0.1,
                       "x_ohm_per_km": 0.1,
                       "c_nf_per_km": 0,
                       "max_i_ka": 1000,
                       "r0_ohm_per_km": 0.1,
                       "x0_ohm_per_km": 0.1,
                       "c0_nf_per_km": 0}
        self._1x95_AASC_35_kV = {"r_ohm_per_km": 0.361,
                                 "x_ohm_per_km": 0.3631,
                                 "c_nf_per_km": 0.011,
                                 "max_i_ka": 0.32,
                                 "r0_ohm_per_km": 0.509,
                                 "x0_ohm_per_km": 1.5763,
                                 "c0_nf_per_km": 0.008}
        self._3x1xNA2XSopeningbracketFclosingbracket2Y185_6per10_kV = {"r_ohm_per_km": 0.157,
                                                                       "x_ohm_per_km": 0.119,
                                                                       "c_nf_per_km": 0.281,
                                                                       "max_i_ka": 0.357,
                                                                       "r0_ohm_per_km": 0.884,
                                                                       "x0_ohm_per_km": 0.052,
                                                                       "c0_nf_per_km": 0.156}
        self._3x1xNA2XSopeningbracketFclosingbracket2Y240_12per20_kV = {"r_ohm_per_km": 0.125,
                                                                        "x_ohm_per_km": 0.115,
                                                                        "c_nf_per_km": 0.3,
                                                                        "max_i_ka": 0.421,
                                                                        "r0_ohm_per_km": 0.852,
                                                                        "x0_ohm_per_km": 0.0497,
                                                                        "c0_nf_per_km": 0.167}
        self._3x1xNA2XSopeningbracketFclosingbracket2Y240_6per10_kV = {"r_ohm_per_km": 0.125,
                                                                       "x_ohm_per_km": 0.1084,
                                                                       "c_nf_per_km": 0.44,
                                                                       "max_i_ka": 0.416,
                                                                       "r0_ohm_per_km": 0.852,
                                                                       "x0_ohm_per_km": 0.0451,
                                                                       "c0_nf_per_km": 0.25}
        self._3x1xNA2XSopeningbracketFclosingbracket2Y500_12per20_kV = {"r_ohm_per_km": 0.0623,
                                                                        "x_ohm_per_km": 0.1019,
                                                                        "c_nf_per_km": 0.4,
                                                                        "max_i_ka": 0.606,
                                                                        "r0_ohm_per_km": 0.7893,
                                                                        "x0_ohm_per_km": 0.0408,
                                                                        "c0_nf_per_km": 0.4}
        self._3x1xNA2XSopeningbracketFclosingbracket2Y95_12per20_kV = {"r_ohm_per_km": 0.32,
                                                                       "x_ohm_per_km": 0.134,
                                                                       "c_nf_per_km": 0.21,
                                                                       "max_i_ka": 0.252,
                                                                       "r0_ohm_per_km": 1.47,
                                                                       "x0_ohm_per_km": 0.0637,
                                                                       "c0_nf_per_km": 0.21}
        self._3x1xNA2XSopeningbracketFclosingbracket2Y95_6per10_kV = {"r_ohm_per_km": 0.32,
                                                                      "x_ohm_per_km": 0.1261,
                                                                      "c_nf_per_km": 0.31,
                                                                      "max_i_ka": 0.249,
                                                                      "r0_ohm_per_km": 1.47,
                                                                      "x0_ohm_per_km": 0.0577,
                                                                      "c0_nf_per_km": 0.21}
        self._3x1xNA2XSopeningbracketFclosingbracketY150_12per20_kV = {"r_ohm_per_km": 0.206,
                                                                       "x_ohm_per_km": 0.1245,
                                                                       "c_nf_per_km": 0.25,
                                                                       "max_i_ka": 0.32,
                                                                       "r0_ohm_per_km": 0.933,
                                                                       "x0_ohm_per_km": 0.0566,
                                                                       "c0_nf_per_km": 0.139}
        self._3x1xNA2XSopeningbracketFclosingbracketY150_6per10_kV = {"r_ohm_per_km": 0.206,
                                                                      "x_ohm_per_km": 0.1172,
                                                                      "c_nf_per_km": 0.36,
                                                                      "max_i_ka": 0.316,
                                                                      "r0_ohm_per_km": 0.933,
                                                                      "x0_ohm_per_km": 0.0513,
                                                                      "c0_nf_per_km": 0.25}
        self._3x1xNA2XSopeningbracketFclosingbracketY240_12per20_kV = {"r_ohm_per_km": 0.125,
                                                                       "x_ohm_per_km": 0.115,
                                                                       "c_nf_per_km": 0.3,
                                                                       "max_i_ka": 0.421,
                                                                       "r0_ohm_per_km": 0.852,
                                                                       "x0_ohm_per_km": 0.0497,
                                                                       "c0_nf_per_km": 0.167}
        self._3x1xNA2XSopeningbracketFclosingbracketY240_6per10_kV = {"r_ohm_per_km": 0.125,
                                                                      "x_ohm_per_km": 0.1084,
                                                                      "c_nf_per_km": 0.44,
                                                                      "max_i_ka": 0.416,
                                                                      "r0_ohm_per_km": 0.852,
                                                                      "x0_ohm_per_km": 0.0451,
                                                                      "c0_nf_per_km": 0.25}
        self._3x1xNA2XSopeningbracketFclosingbracket2Y300_6per10_kV = {"r_ohm_per_km": 0.103,
                                                                       "x_ohm_per_km": 0.0974,
                                                                       "c_nf_per_km": 0.51,
                                                                       "max_i_ka": 0.474,
                                                                       "r0_ohm_per_km": 0.702,
                                                                       "x0_ohm_per_km": 0.0396,
                                                                       "c0_nf_per_km": 0.266}
        self._3x1xNA2XSopeningbracketFclosingbracketY95_12per20_kV = {"r_ohm_per_km": 0.32,
                                                                      "x_ohm_per_km": 0.134,
                                                                      "c_nf_per_km": 0.21,
                                                                      "max_i_ka": 0.252,
                                                                      "r0_ohm_per_km": 1.47,
                                                                      "x0_ohm_per_km": 0.0637,
                                                                      "c0_nf_per_km": 0.21}
        self._3x240_ASC_22_kV = {"r_ohm_per_km": 0.125,
                                 "x_ohm_per_km": 0.3327,
                                 "c_nf_per_km": 0.011,
                                 "max_i_ka": 0.595,
                                 "r0_ohm_per_km": 0.273,
                                 "x0_ohm_per_km": 1.546,
                                 "c0_nf_per_km": 0.009}
        self._3x25_AASC_11_kV = {"r_ohm_per_km": 1.37,
                                 "x_ohm_per_km": 0.4089,
                                 "c_nf_per_km": 0.01,
                                 "max_i_ka": 0.135,
                                 "r0_ohm_per_km": 1.518,
                                 "x0_ohm_per_km": 1.6222,
                                 "c0_nf_per_km": 0.007}
        self._3x25_AASC_22_kV = {"r_ohm_per_km": 1.37,
                                 "x_ohm_per_km": 0.4089,
                                 "c_nf_per_km": 0.01,
                                 "max_i_ka": 0.135,
                                 "r0_ohm_per_km": 1.518,
                                 "x0_ohm_per_km": 1.6222,
                                 "c0_nf_per_km": 0.007}
        self._3x25_ACSR_22_kV = {"r_ohm_per_km": 1.208,
                                 "x_ohm_per_km": 0.4089,
                                 "c_nf_per_km": 0.01,
                                 "max_i_ka": 0.14,
                                 "r0_ohm_per_km": 1.356,
                                 "x0_ohm_per_km": 1.6222,
                                 "c0_nf_per_km": 0.007}
        self._3x25_ASC_22_kV = {"r_ohm_per_km": 1.171,
                                "x_ohm_per_km": 0.4089,
                                "c_nf_per_km": 0.01,
                                "max_i_ka": 0.14,
                                "r0_ohm_per_km": 1.319,
                                "x0_ohm_per_km": 1.6222,
                                "c0_nf_per_km": 0.007}
        self._3x1xNA2XSopeningbracketFclosingbracket2Y150_12per20_kV = {"r_ohm_per_km": 0.206,
                                                                        "x_ohm_per_km": 0.1245,
                                                                        "c_nf_per_km": 0.25,
                                                                        "max_i_ka": 0.32,
                                                                        "r0_ohm_per_km": 0.933,
                                                                        "x0_ohm_per_km": 0.0566,
                                                                        "c0_nf_per_km": 0.139}
        self._3x1xNA2XSopeningbracketFclosingbracket2Y150_6per10_kV = {"r_ohm_per_km": 0.206,
                                                                       "x_ohm_per_km": 0.1172,
                                                                       "c_nf_per_km": 0.36,
                                                                       "max_i_ka": 0.316,
                                                                       "r0_ohm_per_km": 0.933,
                                                                       "x0_ohm_per_km": 0.0513,
                                                                       "c0_nf_per_km": 0.25}
        self._3x250_ACSR_35_kV = {"r_ohm_per_km": 0.116,
                                  "x_ohm_per_km": 0.2762,
                                  "c_nf_per_km": 0.01,
                                  "max_i_ka": 0.66,
                                  "r0_ohm_per_km": 0.264,
                                  "x0_ohm_per_km": 1.6556,
                                  "c0_nf_per_km": 0.009}
        self._3x35_AASC_11_kV = {"r_ohm_per_km": 0.967,
                                 "x_ohm_per_km": 0.3981,
                                 "c_nf_per_km": 0.01,
                                 "max_i_ka": 0.17,
                                 "r0_ohm_per_km": 1.115,
                                 "x0_ohm_per_km": 1.6113,
                                 "c0_nf_per_km": 0.007}
        self._3x35_AASC_22_kV = {"r_ohm_per_km": 0.967,
                                 "x_ohm_per_km": 0.3981,
                                 "c_nf_per_km": 0.01,
                                 "max_i_ka": 0.17,
                                 "r0_ohm_per_km": 1.115,
                                 "x0_ohm_per_km": 1.6113,
                                 "c0_nf_per_km": 0.007}
        self._3x35_ASC_22_kV = {"r_ohm_per_km": 0.825,
                                "x_ohm_per_km": 0.3981,
                                "c_nf_per_km": 0.01,
                                "max_i_ka": 0.175,
                                "r0_ohm_per_km": 0.973,
                                "x0_ohm_per_km": 1.6113,
                                "c0_nf_per_km": 0.007}
        self._3x35_Cu_22_kV = {"r_ohm_per_km": 0.524,
                               "x_ohm_per_km": 0.3981,
                               "c_nf_per_km": 0.01,
                               "max_i_ka": 0.157,
                               "r0_ohm_per_km": 0.672,
                               "x0_ohm_per_km": 1.6113,
                               "c0_nf_per_km": 0.007}
        self._3x50_AASC_11_kV = {"r_ohm_per_km": 0.672,
                                 "x_ohm_per_km": 0.3865,
                                 "c_nf_per_km": 0.01,
                                 "max_i_ka": 0.21,
                                 "r0_ohm_per_km": 0.82,
                                 "x0_ohm_per_km": 1.5997,
                                 "c0_nf_per_km": 0.007}
        self._3x50_AASC_22_kV = {"r_ohm_per_km": 0.672,
                                 "x_ohm_per_km": 0.3865,
                                 "c_nf_per_km": 0.01,
                                 "max_i_ka": 0.21,
                                 "r0_ohm_per_km": 0.82,
                                 "x0_ohm_per_km": 1.5997,
                                 "c0_nf_per_km": 0.007}
        self._3x50_AASC_35_kV = {"r_ohm_per_km": 0.672,
                                 "x_ohm_per_km": 0.3865,
                                 "c_nf_per_km": 0.009,
                                 "max_i_ka": 0.21,
                                 "r0_ohm_per_km": 0.82,
                                 "x0_ohm_per_km": 1.5997,
                                 "c0_nf_per_km": 0.008}
        self._3x50_ACSR_22_kV = {"r_ohm_per_km": 0.597,
                                 "x_ohm_per_km": 0.3865,
                                 "c_nf_per_km": 0.01,
                                 "max_i_ka": 0.21,
                                 "r0_ohm_per_km": 0.745,
                                 "x0_ohm_per_km": 1.5997,
                                 "c0_nf_per_km": 0.007}
        self._3x50_ASC_22_kV = {"r_ohm_per_km": 0.573,
                                "x_ohm_per_km": 0.3865,
                                "c_nf_per_km": 0.01,
                                "max_i_ka": 0.22,
                                "r0_ohm_per_km": 0.721,
                                "x0_ohm_per_km": 1.5997,
                                "c0_nf_per_km": 0.007}
        self._3x50_ASC_35_kV = {"r_ohm_per_km": 0.573,
                                "x_ohm_per_km": 0.3865,
                                "c_nf_per_km": 0.009,
                                "max_i_ka": 0.22,
                                "r0_ohm_per_km": 0.721,
                                "x0_ohm_per_km": 1.5997,
                                "c0_nf_per_km": 0.008}
        self._3x50_Cu_22_kV = {"r_ohm_per_km": 0.387,
                               "x_ohm_per_km": 0.3865,
                               "c_nf_per_km": 0.01,
                               "max_i_ka": 0.223,
                               "r0_ohm_per_km": 0.535,
                               "x0_ohm_per_km": 1.5997,
                               "c0_nf_per_km": 0.007}
        self._3x50_Nikal_22_kV = {"r_ohm_per_km": 0.677,
                                  "x_ohm_per_km": 0.3865,
                                  "c_nf_per_km": 0.01,
                                  "max_i_ka": 0.21,
                                  "r0_ohm_per_km": 0.825,
                                  "x0_ohm_per_km": 1.5997,
                                  "c0_nf_per_km": 0.007}
        self._3x70_AASC_22_kV = {"r_ohm_per_km": 0.511,
                                 "x_ohm_per_km": 0.3741,
                                 "c_nf_per_km": 0.011,
                                 "max_i_ka": 0.255,
                                 "r0_ohm_per_km": 0.659,
                                 "x0_ohm_per_km": 1.5874,
                                 "c0_nf_per_km": 0.007}
        self._3x70_AASC_35_kV = {"r_ohm_per_km": 0.511,
                                 "x_ohm_per_km": 0.3741,
                                 "c_nf_per_km": 0.009,
                                 "max_i_ka": 0.255,
                                 "r0_ohm_per_km": 0.659,
                                 "x0_ohm_per_km": 1.5874,
                                 "c0_nf_per_km": 0.009}
        self._3x70_ACSR_22_kV = {"r_ohm_per_km": 0.511,
                                 "x_ohm_per_km": 0.3741,
                                 "c_nf_per_km": 0.011,
                                 "max_i_ka": 0.29,
                                 "r0_ohm_per_km": 0.659,
                                 "x0_ohm_per_km": 1.5874,
                                 "c0_nf_per_km": 0.007}
        self._3x70_ASC_22_kV = {"r_ohm_per_km": 0.44,
                                "x_ohm_per_km": 0.3741,
                                "c_nf_per_km": 0.011,
                                "max_i_ka": 0.26,
                                "r0_ohm_per_km": 0.588,
                                "x0_ohm_per_km": 1.5874,
                                "c0_nf_per_km": 0.007}
        self._3x95_AASC_11_kV = {"r_ohm_per_km": 0.361,
                                 "x_ohm_per_km": 0.3631,
                                 "c_nf_per_km": 0.011,
                                 "max_i_ka": 0.32,
                                 "r0_ohm_per_km": 0.509,
                                 "x0_ohm_per_km": 1.5763,
                                 "c0_nf_per_km": 0.008}
        self._3x95_AASC_22_kV = {"r_ohm_per_km": 0.361,
                                 "x_ohm_per_km": 0.3631,
                                 "c_nf_per_km": 0.011,
                                 "max_i_ka": 0.32,
                                 "r0_ohm_per_km": 0.509,
                                 "x0_ohm_per_km": 1.5763,
                                 "c0_nf_per_km": 0.008}
        self._3x95_AASC_35_kV = {"r_ohm_per_km": 0.361,
                                 "x_ohm_per_km": 0.3631,
                                 "c_nf_per_km": 0.009,
                                 "max_i_ka": 0.32,
                                 "r0_ohm_per_km": 0.509,
                                 "x0_ohm_per_km": 1.5763,
                                 "c0_nf_per_km": 0.009}
        self._3x95_ACSR_22_kV = {"r_ohm_per_km": 0.307,
                                 "x_ohm_per_km": 0.3631,
                                 "c_nf_per_km": 0.011,
                                 "max_i_ka": 0.35,
                                 "r0_ohm_per_km": 0.455,
                                 "x0_ohm_per_km": 1.5763,
                                 "c0_nf_per_km": 0.008}
        self._3x95_ACSR_35_kV = {"r_ohm_per_km": 0.307,
                                 "x_ohm_per_km": 0.3631,
                                 "c_nf_per_km": 0.009,
                                 "max_i_ka": 0.35,
                                 "r0_ohm_per_km": 0.455,
                                 "x0_ohm_per_km": 1.5763,
                                 "c0_nf_per_km": 0.009}
        self._3x95_AL59_22_kV = {"r_ohm_per_km": 0.32,
                                 "x_ohm_per_km": 0.3631,
                                 "c_nf_per_km": 0.011,
                                 "max_i_ka": 0.195,
                                 "r0_ohm_per_km": 0.468,
                                 "x0_ohm_per_km": 1.5763,
                                 "c0_nf_per_km": 0.008}
        self._3x95_ASC_22_kV = {"r_ohm_per_km": 0.311,
                                "x_ohm_per_km": 0.3631,
                                "c_nf_per_km": 0.011,
                                "max_i_ka": 0.33,
                                "r0_ohm_per_km": 0.459,
                                "x0_ohm_per_km": 1.5763,
                                "c0_nf_per_km": 0.008}
        self._3x95_ASC_35_kV = {"r_ohm_per_km": 0.311,
                                "x_ohm_per_km": 0.3631,
                                "c_nf_per_km": 0.009,
                                "max_i_ka": 0.33,
                                "r0_ohm_per_km": 0.459,
                                "x0_ohm_per_km": 1.5763,
                                "c0_nf_per_km": 0.009}
        self._3x95_Nikal_22_kV = {"r_ohm_per_km": 0.362,
                                  "x_ohm_per_km": 0.3631,
                                  "c_nf_per_km": 0.011,
                                  "max_i_ka": 0.32,
                                  "r0_ohm_per_km": 0.51,
                                  "x0_ohm_per_km": 1.5763,
                                  "c0_nf_per_km": 0.007}
        self._Htip150_11_kV = {"r_ohm_per_km": 0.206,
                               "x_ohm_per_km": 0.1172,
                               "c_nf_per_km": 0.38,
                               "max_i_ka": 0.259,
                               "r0_ohm_per_km": 0.2905,
                               "x0_ohm_per_km": 0.0513,
                               "c0_nf_per_km": 0.445}
        self._3x1xNA2XS2Y50_20per35_kV_RMper16 = {"r_ohm_per_km": 0.641,
                                                  "x_ohm_per_km": 0.1539,
                                                  "c_nf_per_km": 0.14,
                                                  "max_i_ka": 0.175,
                                                  "r0_ohm_per_km": 1.1005,
                                                  "x0_ohm_per_km": 0.0762,
                                                  "c0_nf_per_km": 0.277}
        self._3x1xNA2XSopeningbracketFclosingbracketY50_12per20_kV = {"r_ohm_per_km": 0.641,
                                                                      "x_ohm_per_km": 0.1539,
                                                                      "c_nf_per_km": 0.14,
                                                                      "max_i_ka": 0.175,
                                                                      "r0_ohm_per_km": 1.1005,
                                                                      "x0_ohm_per_km": 0.0762,
                                                                      "c0_nf_per_km": 0.277}
        self._3x1xNA2XSopeningbracketFclosingbracket2Y300_12per22_kV = {"r_ohm_per_km": 0.103,
                                                                        "x_ohm_per_km": 0.0974,
                                                                        "c_nf_per_km": 0.51,
                                                                        "max_i_ka": 0.474,
                                                                        "r0_ohm_per_km": 0.702,
                                                                        "x0_ohm_per_km": 0.0396,
                                                                        "c0_nf_per_km": 0.266}
        self._3x1xA2XSopeningbracketFclosingbracket2Y50_20per35_kV_RM16 = {"r_ohm_per_km": 0.641,
                                                                           "x_ohm_per_km": 0.1539,
                                                                           "c_nf_per_km": 0.14,
                                                                           "max_i_ka": 0.175,
                                                                           "r0_ohm_per_km": 1.1005,
                                                                           "x0_ohm_per_km": 0.0762,
                                                                           "c0_nf_per_km": 0.277}
        self._3x1xNA2XSopeningbracketFclosingbracket2Y150_20per35_kV = {"r_ohm_per_km": 0.206,
                                                                        "x_ohm_per_km": 0.1245,
                                                                        "c_nf_per_km": 0.25,
                                                                        "max_i_ka": 0.32,
                                                                        "r0_ohm_per_km": 0.933,
                                                                        "x0_ohm_per_km": 0.0566,
                                                                        "c0_nf_per_km": 0.139}
        self._Alukabel_120_11_kV = {"r_ohm_per_km": 0.253,
                                    "x_ohm_per_km": 0.1213,
                                    "c_nf_per_km": 0.35,
                                    "max_i_ka": 0.225,
                                    "r0_ohm_per_km": 0.3439,
                                    "x0_ohm_per_km": 0.0542,
                                    "c0_nf_per_km": 0.225}
        self._Alukabel_120_22_kV = {"r_ohm_per_km": 0.253,
                                    "x_ohm_per_km": 0.1289,
                                    "c_nf_per_km": 0.23,
                                    "max_i_ka": 0.23,
                                    "r0_ohm_per_km": 0.334,
                                    "x0_ohm_per_km": 0.0598,
                                    "c0_nf_per_km": 0.12}
        self._Alukabel_150_11_kV = {"r_ohm_per_km": 0.206,
                                    "x_ohm_per_km": 0.1172,
                                    "c_nf_per_km": 0.38,
                                    "max_i_ka": 0.255,
                                    "r0_ohm_per_km": 0.2905,
                                    "x0_ohm_per_km": 0.0513,
                                    "c0_nf_per_km": 0.25}
        self._Alukabel_150_22_kV = {"r_ohm_per_km": 0.206,
                                    "x_ohm_per_km": 0.1245,
                                    "c_nf_per_km": 0.251,
                                    "max_i_ka": 0.26,
                                    "r0_ohm_per_km": 0.2929,
                                    "x0_ohm_per_km": 0.0566,
                                    "c0_nf_per_km": 0.254}
        self._Alukabel_185_11_kV = {"r_ohm_per_km": 0.164,
                                    "x_ohm_per_km": 0.1132,
                                    "c_nf_per_km": 0.4,
                                    "max_i_ka": 0.285,
                                    "r0_ohm_per_km": 0.2477,
                                    "x0_ohm_per_km": 0.0485,
                                    "c0_nf_per_km": 0.275}
        self._Alukabel_185_22_kV = {"r_ohm_per_km": 0.164,
                                    "x_ohm_per_km": 0.1202,
                                    "c_nf_per_km": 0.27,
                                    "max_i_ka": 0.29,
                                    "r0_ohm_per_km": 0.2371,
                                    "x0_ohm_per_km": 0.0534,
                                    "c0_nf_per_km": 0.105}
        self._Alukabel_240_11_kV = {"r_ohm_per_km": 0.125,
                                    "x_ohm_per_km": 0.1084,
                                    "c_nf_per_km": 0.46,
                                    "max_i_ka": 0.33,
                                    "r0_ohm_per_km": 0.2025,
                                    "x0_ohm_per_km": 0.0451,
                                    "c0_nf_per_km": 0.3}
        self._Alukabel_240_22_kV = {"r_ohm_per_km": 0.125,
                                    "x_ohm_per_km": 0.115,
                                    "c_nf_per_km": 0.3,
                                    "max_i_ka": 0.34,
                                    "r0_ohm_per_km": 0.1947,
                                    "x0_ohm_per_km": 0.0497,
                                    "c0_nf_per_km": 0.167}
        self._Alukabel_50_22_kV = {"r_ohm_per_km": 0.641,
                                   "x_ohm_per_km": 0.1501,
                                   "c_nf_per_km": 0.18,
                                   "max_i_ka": 0.135,
                                   "r0_ohm_per_km": 0.7324,
                                   "x0_ohm_per_km": 0.0763,
                                   "c0_nf_per_km": 0.43}
        self._Alukabel_500_11_kV = {"r_ohm_per_km": 0.0623,
                                    "x_ohm_per_km": 0.0962,
                                    "c_nf_per_km": 0.61,
                                    "max_i_ka": 0.622,
                                    "r0_ohm_per_km": 0.1067,
                                    "x0_ohm_per_km": 0.0371,
                                    "c0_nf_per_km": 0.35}
        self._Alukabel_70_22_kV = {"r_ohm_per_km": 0.443,
                                   "x_ohm_per_km": 0.1412,
                                   "c_nf_per_km": 0.2,
                                   "max_i_ka": 0.17,
                                   "r0_ohm_per_km": 0.5299,
                                   "x0_ohm_per_km": 0.0693,
                                   "c0_nf_per_km": 0.48}
        self._Alukabel_95_11_kV = {"r_ohm_per_km": 0.32,
                                   "x_ohm_per_km": 0.1261,
                                   "c_nf_per_km": 0.32,
                                   "max_i_ka": 0.195,
                                   "r0_ohm_per_km": 0.4167,
                                   "x0_ohm_per_km": 0.0577,
                                   "c0_nf_per_km": 0.2}
        self._Alukabel_95_22_kV = {"r_ohm_per_km": 0.32,
                                   "x_ohm_per_km": 0.134,
                                   "c_nf_per_km": 0.22,
                                   "max_i_ka": 0.195,
                                   "r0_ohm_per_km": 0.4021,
                                   "x0_ohm_per_km": 0.0637,
                                   "c0_nf_per_km": 0.08}
        self._AOSZB_150_22_kV = {"r_ohm_per_km": 0.206,
                                 "x_ohm_per_km": 0.1245,
                                 "c_nf_per_km": 0.25,
                                 "max_i_ka": 0.267,
                                 "r0_ohm_per_km": 0.2815,
                                 "x0_ohm_per_km": 0.0566,
                                 "c0_nf_per_km": 0.139}
        self._AOSZB_185_22_kV = {"r_ohm_per_km": 0.164,
                                 "x_ohm_per_km": 0.1202,
                                 "c_nf_per_km": 0.27,
                                 "max_i_ka": 0.304,
                                 "r0_ohm_per_km": 0.2371,
                                 "x0_ohm_per_km": 0.0534,
                                 "c0_nf_per_km": 0.139}
        self._AOSZB_240_11_kV = {"r_ohm_per_km": 0.125,
                                 "x_ohm_per_km": 0.1084,
                                 "c_nf_per_km": 0.67,
                                 "max_i_ka": 0.343,
                                 "r0_ohm_per_km": 0.2025,
                                 "x0_ohm_per_km": 0.0451,
                                 "c0_nf_per_km": 0.3}
        self._ASZB_120_11_kV = {"r_ohm_per_km": 0.253,
                                "x_ohm_per_km": 0.1213,
                                "c_nf_per_km": 0.46,
                                "max_i_ka": 0.229,
                                "r0_ohm_per_km": 0.3439,
                                "x0_ohm_per_km": 0.0542,
                                "c0_nf_per_km": 0.405}
        self._ASZB_150_11_kV = {"r_ohm_per_km": 0.206,
                                "x_ohm_per_km": 0.1172,
                                "c_nf_per_km": 0.54,
                                "max_i_ka": 0.259,
                                "r0_ohm_per_km": 0.2905,
                                "x0_ohm_per_km": 0.0513,
                                "c0_nf_per_km": 0.25}
        self._ASZB_150_22_kV = {"r_ohm_per_km": 0.206,
                                "x_ohm_per_km": 0.1245,
                                "c_nf_per_km": 0.25,
                                "max_i_ka": 0.267,
                                "r0_ohm_per_km": 0.2815,
                                "x0_ohm_per_km": 0.0566,
                                "c0_nf_per_km": 0.139}
        self._ASZB_185_11_kV = {"r_ohm_per_km": 0.164,
                                "x_ohm_per_km": 0.1132,
                                "c_nf_per_km": 0.56,
                                "max_i_ka": 0.295,
                                "r0_ohm_per_km": 0.2477,
                                "x0_ohm_per_km": 0.0485,
                                "c0_nf_per_km": 0.276}
        self._ASZB_240_11_kV = {"r_ohm_per_km": 0.125,
                                "x_ohm_per_km": 0.1084,
                                "c_nf_per_km": 0.67,
                                "max_i_ka": 0.343,
                                "r0_ohm_per_km": 0.2025,
                                "x0_ohm_per_km": 0.0451,
                                "c0_nf_per_km": 0.3}
        self._ASZB_240_22_kV = {"r_ohm_per_km": 0.125,
                                "x_ohm_per_km": 0.115,
                                "c_nf_per_km": 0.3,
                                "max_i_ka": 0.267,
                                "r0_ohm_per_km": 0.1947,
                                "x0_ohm_per_km": 0.0497,
                                "c0_nf_per_km": 0.167}
        self._AXCES_3x70per16_14per24_kV_foldben = {"r_ohm_per_km": 0.44,
                                                    "x_ohm_per_km": 0.115,
                                                    "c_nf_per_km": 0.18,
                                                    "max_i_ka": 0.19,
                                                    "r0_ohm_per_km": 0.7324,
                                                    "x0_ohm_per_km": 0.0763,
                                                    "c0_nf_per_km": 0.43}
        self._AXCES_3x70per16_14per24_kV_levegoben = {"r_ohm_per_km": 0.44,
                                                      "x_ohm_per_km": 0.115,
                                                      "c_nf_per_km": 0.18,
                                                      "max_i_ka": 0.16,
                                                      "r0_ohm_per_km": 0.7324,
                                                      "x0_ohm_per_km": 0.0763,
                                                      "c0_nf_per_km": 0.43}
        self._AXCES_3x95per25_14per24_kV_foldben = {"r_ohm_per_km": 0.32,
                                                    "x_ohm_per_km": 0.0974,
                                                    "c_nf_per_km": 0.25,
                                                    "max_i_ka": 0.24,
                                                    "r0_ohm_per_km": 1.47,
                                                    "x0_ohm_per_km": 0.0637,
                                                    "c0_nf_per_km": 0.21}
        self._AXCES_3x95per25_14per24_kV_levegoben = {"r_ohm_per_km": 0.32,
                                                      "x_ohm_per_km": 0.0974,
                                                      "c_nf_per_km": 0.25,
                                                      "max_i_ka": 0.2,
                                                      "r0_ohm_per_km": 1.47,
                                                      "x0_ohm_per_km": 0.0637,
                                                      "c0_nf_per_km": 0.21}
        self._BSZV_3x150_12per20_kV = {"r_ohm_per_km": 0.2281,
                                       "x_ohm_per_km": 0.2924,
                                       "c_nf_per_km": 0.012,
                                       "max_i_ka": 0.426,
                                       "r0_ohm_per_km": 0.3761,
                                       "x0_ohm_per_km": 1.6714,
                                       "c0_nf_per_km": 0.008}
        self._BSZV_3x50_12per20_kV = {"r_ohm_per_km": 0.6829,
                                      "x_ohm_per_km": 0.3312,
                                      "c_nf_per_km": 0.01,
                                      "max_i_ka": 0.214,
                                      "r0_ohm_per_km": 0.8309,
                                      "x0_ohm_per_km": 1.7102,
                                      "c0_nf_per_km": 0.007}
        self._BSZV_3x50_6per12_kV = {"r_ohm_per_km": 0.6829,
                                     "x_ohm_per_km": 0.3312,
                                     "c_nf_per_km": 0.01,
                                     "max_i_ka": 0.214,
                                     "r0_ohm_per_km": 0.8309,
                                     "x0_ohm_per_km": 1.7102,
                                     "c0_nf_per_km": 0.007}
        self._BSZV_3x95_12per20_kV = {"r_ohm_per_km": 0.3622,
                                      "x_ohm_per_km": 0.3079,
                                      "c_nf_per_km": 0.011,
                                      "max_i_ka": 0.32,
                                      "r0_ohm_per_km": 0.5102,
                                      "x0_ohm_per_km": 1.6869,
                                      "c0_nf_per_km": 0.008}
        self._BSZV_3x95_6per12_kV = {"r_ohm_per_km": 0.3622,
                                     "x_ohm_per_km": 0.3079,
                                     "c_nf_per_km": 0.011,
                                     "max_i_ka": 0.32,
                                     "r0_ohm_per_km": 0.5102,
                                     "x0_ohm_per_km": 1.6869,
                                     "c0_nf_per_km": 0.007}
        self._EPEE150_11_kV = {"r_ohm_per_km": 0.206,
                               "x_ohm_per_km": 0.177,
                               "c_nf_per_km": 0.38,
                               "max_i_ka": 0.315,
                               "r0_ohm_per_km": 0.3112,
                               "x0_ohm_per_km": 0.0513,
                               "c0_nf_per_km": 0.375}
        self._EPEE150_22_kV = {"r_ohm_per_km": 0.206,
                               "x_ohm_per_km": 0.177,
                               "c_nf_per_km": 0.251,
                               "max_i_ka": 0.39,
                               "r0_ohm_per_km": 0.2929,
                               "x0_ohm_per_km": 0.0566,
                               "c0_nf_per_km": 0.254}
        self._EPEE240_11_kV = {"r_ohm_per_km": 0.125,
                               "x_ohm_per_km": 0.1617,
                               "c_nf_per_km": 0.46,
                               "max_i_ka": 0.409,
                               "r0_ohm_per_km": 0.2119,
                               "x0_ohm_per_km": 0.0451,
                               "c0_nf_per_km": 0.458}
        self._EPEE240_22_kV = {"r_ohm_per_km": 0.125,
                               "x_ohm_per_km": 0.1617,
                               "c_nf_per_km": 0.304,
                               "max_i_ka": 0.504,
                               "r0_ohm_per_km": 0.199,
                               "x0_ohm_per_km": 0.0497,
                               "c0_nf_per_km": 0.304}
        self._EPEH150_11_kV = {"r_ohm_per_km": 0.206,
                               "x_ohm_per_km": 0.1172,
                               "c_nf_per_km": 0.38,
                               "max_i_ka": 0.285,
                               "r0_ohm_per_km": 0.3112,
                               "x0_ohm_per_km": 0.0513,
                               "c0_nf_per_km": 0.375}
        self._EPEH150_22_kV = {"r_ohm_per_km": 0.206,
                               "x_ohm_per_km": 0.1245,
                               "c_nf_per_km": 0.251,
                               "max_i_ka": 0.353,
                               "r0_ohm_per_km": 0.2929,
                               "x0_ohm_per_km": 0.0566,
                               "c0_nf_per_km": 0.254}
        self._EPEH150_35_kV = {"r_ohm_per_km": 0.206,
                               "x_ohm_per_km": 0.1345,
                               "c_nf_per_km": 0.19,
                               "max_i_ka": 0.324,
                               "r0_ohm_per_km": 0.2726,
                               "x0_ohm_per_km": 0.0641,
                               "c0_nf_per_km": 0.345}
        self._EPEH185_11_kV = {"r_ohm_per_km": 0.164,
                               "x_ohm_per_km": 0.1132,
                               "c_nf_per_km": 0.4,
                               "max_i_ka": 0.32,
                               "r0_ohm_per_km": 0.264,
                               "x0_ohm_per_km": 0.0485,
                               "c0_nf_per_km": 0.408}
        self._EPEH185_22_kV = {"r_ohm_per_km": 0.164,
                               "x_ohm_per_km": 0.1202,
                               "c_nf_per_km": 0.276,
                               "max_i_ka": 0.396,
                               "r0_ohm_per_km": 0.244,
                               "x0_ohm_per_km": 0.0534,
                               "c0_nf_per_km": 0.273}
        self._EPEH240_11_kV = {"r_ohm_per_km": 0.125,
                               "x_ohm_per_km": 0.1084,
                               "c_nf_per_km": 0.46,
                               "max_i_ka": 0.37,
                               "r0_ohm_per_km": 0.2119,
                               "x0_ohm_per_km": 0.0451,
                               "c0_nf_per_km": 0.458}
        self._EPEH240_22_kV = {"r_ohm_per_km": 0.125,
                               "x_ohm_per_km": 0.115,
                               "c_nf_per_km": 0.304,
                               "max_i_ka": 0.457,
                               "r0_ohm_per_km": 0.199,
                               "x0_ohm_per_km": 0.0497,
                               "c0_nf_per_km": 0.304}
        self._EPEH95_22_kV = {"r_ohm_per_km": 0.32,
                              "x_ohm_per_km": 0.134,
                              "c_nf_per_km": 0.218,
                              "max_i_ka": 0.282,
                              "r0_ohm_per_km": 0.42,
                              "x0_ohm_per_km": 0.0637,
                              "c0_nf_per_km": 0.215}
        self._ETHE120_22_kV = {"r_ohm_per_km": 0.253,
                               "x_ohm_per_km": 0.1838,
                               "c_nf_per_km": 0.23,
                               "max_i_ka": 0.317,
                               "r0_ohm_per_km": 0.3439,
                               "x0_ohm_per_km": 0.0598,
                               "c0_nf_per_km": 0.235}
        self._ETHE120_35_kV = {"r_ohm_per_km": 0.253,
                               "x_ohm_per_km": 0.1838,
                               "c_nf_per_km": 0.18,
                               "max_i_ka": 0.321,
                               "r0_ohm_per_km": 0.3244,
                               "x0_ohm_per_km": 0.0678,
                               "c0_nf_per_km": 0.32}
        self._ETHE150_11_kV = {"r_ohm_per_km": 0.206,
                               "x_ohm_per_km": 0.177,
                               "c_nf_per_km": 0.38,
                               "max_i_ka": 0.353,
                               "r0_ohm_per_km": 0.3112,
                               "x0_ohm_per_km": 0.0513,
                               "c0_nf_per_km": 0.386}
        self._ETHE150_22_kV = {"r_ohm_per_km": 0.206,
                               "x_ohm_per_km": 0.177,
                               "c_nf_per_km": 0.25,
                               "max_i_ka": 0.354,
                               "r0_ohm_per_km": 0.2929,
                               "x0_ohm_per_km": 0.0566,
                               "c0_nf_per_km": 0.251}
        self._ETHE150_35_kV = {"r_ohm_per_km": 0.206,
                               "x_ohm_per_km": 0.177,
                               "c_nf_per_km": 0.19,
                               "max_i_ka": 0.358,
                               "r0_ohm_per_km": 0.2726,
                               "x0_ohm_per_km": 0.0641,
                               "c0_nf_per_km": 0.345}
        self._ETHE185_11_kV = {"r_ohm_per_km": 0.164,
                               "x_ohm_per_km": 0.1701,
                               "c_nf_per_km": 0.4,
                               "max_i_ka": 0.395,
                               "r0_ohm_per_km": 0.264,
                               "x0_ohm_per_km": 0.0485,
                               "c0_nf_per_km": 0.442}
        self._ETHE185_22_kV = {"r_ohm_per_km": 0.164,
                               "x_ohm_per_km": 0.1701,
                               "c_nf_per_km": 0.27,
                               "max_i_ka": 0.4,
                               "r0_ohm_per_km": 0.244,
                               "x0_ohm_per_km": 0.0534,
                               "c0_nf_per_km": 0.276}
        self._ETHE185_35_kV = {"r_ohm_per_km": 0.164,
                               "x_ohm_per_km": 0.1701,
                               "c_nf_per_km": 0.21,
                               "max_i_ka": 0.404,
                               "r0_ohm_per_km": 0.2285,
                               "x0_ohm_per_km": 0.0605,
                               "c0_nf_per_km": 0.37}
        self._ETHE240_11_kV = {"r_ohm_per_km": 0.125,
                               "x_ohm_per_km": 0.1617,
                               "c_nf_per_km": 0.46,
                               "max_i_ka": 0.459,
                               "r0_ohm_per_km": 0.2119,
                               "x0_ohm_per_km": 0.0451,
                               "c0_nf_per_km": 0.469}
        self._ETHE240_22_kV = {"r_ohm_per_km": 0.125,
                               "x_ohm_per_km": 0.1617,
                               "c_nf_per_km": 0.3,
                               "max_i_ka": 0.465,
                               "r0_ohm_per_km": 0.199,
                               "x0_ohm_per_km": 0.0497,
                               "c0_nf_per_km": 0.304}
        self._ETHE240_35_kV = {"r_ohm_per_km": 0.125,
                               "x_ohm_per_km": 0.1617,
                               "c_nf_per_km": 0.23,
                               "max_i_ka": 0.47,
                               "r0_ohm_per_km": 0.1856,
                               "x0_ohm_per_km": 0.0563,
                               "c0_nf_per_km": 0.41}
        self._ETHE300_22_kV = {"r_ohm_per_km": 0.103,
                               "x_ohm_per_km": 0.1546,
                               "c_nf_per_km": 0.34,
                               "max_i_ka": 0.523,
                               "r0_ohm_per_km": 0.1719,
                               "x0_ohm_per_km": 0.0469,
                               "c0_nf_per_km": 0.33}
        self._ETHE95_22_kV = {"r_ohm_per_km": 0.32,
                              "x_ohm_per_km": 0.1913,
                              "c_nf_per_km": 0.22,
                              "max_i_ka": 0.279,
                              "r0_ohm_per_km": 0.42,
                              "x0_ohm_per_km": 0.0637,
                              "c0_nf_per_km": 0.218}
        self._ETHE95_35_kV = {"r_ohm_per_km": 0.32,
                              "x_ohm_per_km": 0.1913,
                              "c_nf_per_km": 0.17,
                              "max_i_ka": 0.256,
                              "r0_ohm_per_km": 0.394,
                              "x0_ohm_per_km": 0.0721,
                              "c0_nf_per_km": 0.295}
        self._ETHH120_22_kV = {"r_ohm_per_km": 0.253,
                               "x_ohm_per_km": 0.1289,
                               "c_nf_per_km": 0.23,
                               "max_i_ka": 0.287,
                               "r0_ohm_per_km": 1.403,
                               "x0_ohm_per_km": 0.0598,
                               "c0_nf_per_km": 0.12}
        self._ETHH150_22_kV = {"r_ohm_per_km": 0.206,
                               "x_ohm_per_km": 0.1245,
                               "c_nf_per_km": 0.25,
                               "max_i_ka": 0.32,
                               "r0_ohm_per_km": 0.933,
                               "x0_ohm_per_km": 0.0566,
                               "c0_nf_per_km": 0.139}
        self._ETHH150_35_kV = {"r_ohm_per_km": 0.206,
                               "x_ohm_per_km": 0.1345,
                               "c_nf_per_km": 0.19,
                               "max_i_ka": 0.324,
                               "r0_ohm_per_km": 0.2726,
                               "x0_ohm_per_km": 0.0641,
                               "c0_nf_per_km": 0.345}
        self._ETHH185_11_kV = {"r_ohm_per_km": 0.164,
                               "x_ohm_per_km": 0.1132,
                               "c_nf_per_km": 0.39,
                               "max_i_ka": 0.358,
                               "r0_ohm_per_km": 0.264,
                               "x0_ohm_per_km": 0.0485,
                               "c0_nf_per_km": 0.276}
        self._ETHH185_22_kV = {"r_ohm_per_km": 0.164,
                               "x_ohm_per_km": 0.1202,
                               "c_nf_per_km": 0.27,
                               "max_i_ka": 0.362,
                               "r0_ohm_per_km": 0.244,
                               "x0_ohm_per_km": 0.0534,
                               "c0_nf_per_km": 0.276}
        self._ETHH240_11_kV = {"r_ohm_per_km": 0.125,
                               "x_ohm_per_km": 0.1084,
                               "c_nf_per_km": 0.44,
                               "max_i_ka": 0.416,
                               "r0_ohm_per_km": 0.852,
                               "x0_ohm_per_km": 0.0451,
                               "c0_nf_per_km": 0.25}
        self._ETHH240_22_kV = {"r_ohm_per_km": 0.125,
                               "x_ohm_per_km": 0.115,
                               "c_nf_per_km": 0.3,
                               "max_i_ka": 0.421,
                               "r0_ohm_per_km": 0.852,
                               "x0_ohm_per_km": 0.0497,
                               "c0_nf_per_km": 0.167}
        self._ETHH240_35_kV = {"r_ohm_per_km": 0.125,
                               "x_ohm_per_km": 0.1242,
                               "c_nf_per_km": 0.23,
                               "max_i_ka": 0.426,
                               "r0_ohm_per_km": 0.1856,
                               "x0_ohm_per_km": 0.0563,
                               "c0_nf_per_km": 0.41}
        self._ETHH95_22_kV = {"r_ohm_per_km": 0.32,
                              "x_ohm_per_km": 0.134,
                              "c_nf_per_km": 0.21,
                              "max_i_ka": 0.252,
                              "r0_ohm_per_km": 1.47,
                              "x0_ohm_per_km": 0.0637,
                              "c0_nf_per_km": 0.21}
        self._Etip150_22_kV = {"r_ohm_per_km": 0.206,
                               "x_ohm_per_km": 0.1245,
                               "c_nf_per_km": 0.25,
                               "max_i_ka": 0.26,
                               "r0_ohm_per_km": 0.2929,
                               "x0_ohm_per_km": 0.0566,
                               "c0_nf_per_km": 0.23}
        self._Etip150_35_kV = {"r_ohm_per_km": 0.206,
                               "x_ohm_per_km": 0.1345,
                               "c_nf_per_km": 0.19,
                               "max_i_ka": 0.245,
                               "r0_ohm_per_km": 0.2726,
                               "x0_ohm_per_km": 0.0641,
                               "c0_nf_per_km": 0.23}
        self._Etip185_22_kV = {"r_ohm_per_km": 0.164,
                               "x_ohm_per_km": 0.1202,
                               "c_nf_per_km": 0.27,
                               "max_i_ka": 0.29,
                               "r0_ohm_per_km": 0.244,
                               "x0_ohm_per_km": 0.0534,
                               "c0_nf_per_km": 0.245}
        self._Etip240_11_kV = {"r_ohm_per_km": 0.125,
                               "x_ohm_per_km": 0.1084,
                               "c_nf_per_km": 0.46,
                               "max_i_ka": 0.343,
                               "r0_ohm_per_km": 0.2119,
                               "x0_ohm_per_km": 0.0451,
                               "c0_nf_per_km": 0.53}
        self._Etip240_22_kV = {"r_ohm_per_km": 0.125,
                               "x_ohm_per_km": 0.115,
                               "c_nf_per_km": 0.3,
                               "max_i_ka": 0.34,
                               "r0_ohm_per_km": 0.199,
                               "x0_ohm_per_km": 0.0497,
                               "c0_nf_per_km": 0.27}
        self._Etip240_35_kV = {"r_ohm_per_km": 0.125,
                               "x_ohm_per_km": 0.1242,
                               "c_nf_per_km": 0.23,
                               "max_i_ka": 0.315,
                               "r0_ohm_per_km": 0.1856,
                               "x0_ohm_per_km": 0.0563,
                               "c0_nf_per_km": 0.27}
        self._HME120_11_kV = {"r_ohm_per_km": 0.253,
                              "x_ohm_per_km": 0.1213,
                              "c_nf_per_km": 0.35,
                              "max_i_ka": 0.225,
                              "r0_ohm_per_km": 0.3367,
                              "x0_ohm_per_km": 0.0542,
                              "c0_nf_per_km": 0.3}
        self._HME120_22_kV = {"r_ohm_per_km": 0.253,
                              "x_ohm_per_km": 0.1289,
                              "c_nf_per_km": 0.23,
                              "max_i_ka": 0.23,
                              "r0_ohm_per_km": 0.334,
                              "x0_ohm_per_km": 0.0598,
                              "c0_nf_per_km": 0.3}
        self._HME150_11_kV = {"r_ohm_per_km": 0.206,
                              "x_ohm_per_km": 0.1172,
                              "c_nf_per_km": 0.38,
                              "max_i_ka": 0.28,
                              "r0_ohm_per_km": 0.933,
                              "x0_ohm_per_km": 0.0513,
                              "c0_nf_per_km": 0.25}
        self._HME150_35_kV = {"r_ohm_per_km": 0.206,
                              "x_ohm_per_km": 0.1345,
                              "c_nf_per_km": 0.19,
                              "max_i_ka": 0.245,
                              "r0_ohm_per_km": 0.2725,
                              "x0_ohm_per_km": 0.0641,
                              "c0_nf_per_km": 0.445}
        self._HME185_11_kV = {"r_ohm_per_km": 0.164,
                              "x_ohm_per_km": 0.1132,
                              "c_nf_per_km": 0.4,
                              "max_i_ka": 0.315,
                              "r0_ohm_per_km": 0.891,
                              "x0_ohm_per_km": 0.0485,
                              "c0_nf_per_km": 0.276}
        self._HME185_22_kV = {"r_ohm_per_km": 0.164,
                              "x_ohm_per_km": 0.1202,
                              "c_nf_per_km": 0.27,
                              "max_i_ka": 0.29,
                              "r0_ohm_per_km": 0.2371,
                              "x0_ohm_per_km": 0.0534,
                              "c0_nf_per_km": 0.48}
        self._HME240_11_kV = {"r_ohm_per_km": 0.125,
                              "x_ohm_per_km": 0.1084,
                              "c_nf_per_km": 0.46,
                              "max_i_ka": 0.37,
                              "r0_ohm_per_km": 0.852,
                              "x0_ohm_per_km": 0.0451,
                              "c0_nf_per_km": 0.3}
        self._HME240_22_kV = {"r_ohm_per_km": 0.125,
                              "x_ohm_per_km": 0.115,
                              "c_nf_per_km": 0.3,
                              "max_i_ka": 0.34,
                              "r0_ohm_per_km": 0.1947,
                              "x0_ohm_per_km": 0.0497,
                              "c0_nf_per_km": 0.53}
        self._HME95_22_kV = {"r_ohm_per_km": 0.32,
                             "x_ohm_per_km": 0.134,
                             "c_nf_per_km": 0.22,
                             "max_i_ka": 0.195,
                             "r0_ohm_per_km": 0.4021,
                             "x0_ohm_per_km": 0.0637,
                             "c0_nf_per_km": 0.28}
        self._HO120_11_kV = {"r_ohm_per_km": 0.253,
                             "x_ohm_per_km": 0.1213,
                             "c_nf_per_km": 0.35,
                             "max_i_ka": 0.229,
                             "r0_ohm_per_km": 0.9802,
                             "x0_ohm_per_km": 0.0542,
                             "c0_nf_per_km": 0.405}
        self._HO120_22_kV = {"r_ohm_per_km": 0.253,
                             "x_ohm_per_km": 0.1289,
                             "c_nf_per_km": 0.23,
                             "max_i_ka": 0.23,
                             "r0_ohm_per_km": 0.9016,
                             "x0_ohm_per_km": 0.0598,
                             "c0_nf_per_km": 0.09}
        self._HO150_11_kV = {"r_ohm_per_km": 0.206,
                             "x_ohm_per_km": 0.1172,
                             "c_nf_per_km": 0.38,
                             "max_i_ka": 0.259,
                             "r0_ohm_per_km": 0.882,
                             "x0_ohm_per_km": 0.0513,
                             "c0_nf_per_km": 0.445}
        self._HO150_22_kV = {"r_ohm_per_km": 0.206,
                             "x_ohm_per_km": 0.1245,
                             "c_nf_per_km": 0.25,
                             "max_i_ka": 0.26,
                             "r0_ohm_per_km": 0.8105,
                             "x0_ohm_per_km": 0.0566,
                             "c0_nf_per_km": 0.1}
        self._HO185_11_kV = {"r_ohm_per_km": 0.164,
                             "x_ohm_per_km": 0.1132,
                             "c_nf_per_km": 0.4,
                             "max_i_ka": 0.295,
                             "r0_ohm_per_km": 0.8343,
                             "x0_ohm_per_km": 0.0485,
                             "c0_nf_per_km": 0.48}
        self._HO185_22_kV = {"r_ohm_per_km": 0.164,
                             "x_ohm_per_km": 0.1202,
                             "c_nf_per_km": 0.27,
                             "max_i_ka": 0.29,
                             "r0_ohm_per_km": 0.7493,
                             "x0_ohm_per_km": 0.0534,
                             "c0_nf_per_km": 0.105}
        self._HO240_11_kV = {"r_ohm_per_km": 0.125,
                             "x_ohm_per_km": 0.1084,
                             "c_nf_per_km": 0.46,
                             "max_i_ka": 0.343,
                             "r0_ohm_per_km": 0.7451,
                             "x0_ohm_per_km": 0.0451,
                             "c0_nf_per_km": 0.53}
        self._HO240_22_kV = {"r_ohm_per_km": 0.125,
                             "x_ohm_per_km": 0.115,
                             "c_nf_per_km": 0.3,
                             "max_i_ka": 0.34,
                             "r0_ohm_per_km": 0.6831,
                             "x0_ohm_per_km": 0.0497,
                             "c0_nf_per_km": 0.11}
        self._HO95_22_kV = {"r_ohm_per_km": 0.32,
                            "x_ohm_per_km": 0.134,
                            "c_nf_per_km": 0.22,
                            "max_i_ka": 0.195,
                            "r0_ohm_per_km": 0.9775,
                            "x0_ohm_per_km": 0.0637,
                            "c0_nf_per_km": 0.08}
        self._Htip120_22_kV = {"r_ohm_per_km": 0.253,
                               "x_ohm_per_km": 0.1289,
                               "c_nf_per_km": 0.23,
                               "max_i_ka": 0.23,
                               "r0_ohm_per_km": 0.334,
                               "x0_ohm_per_km": 0.0598,
                               "c0_nf_per_km": 0.2}
        self._Htip150_22_kV = {"r_ohm_per_km": 0.206,
                               "x_ohm_per_km": 0.1245,
                               "c_nf_per_km": 0.25,
                               "max_i_ka": 0.26,
                               "r0_ohm_per_km": 0.2815,
                               "x0_ohm_per_km": 0.0566,
                               "c0_nf_per_km": 0.23}
        self._Htip150_35_kV = {"r_ohm_per_km": 0.206,
                               "x_ohm_per_km": 0.1345,
                               "c_nf_per_km": 0.19,
                               "max_i_ka": 0.245,
                               "r0_ohm_per_km": 0.2725,
                               "x0_ohm_per_km": 0.0641,
                               "c0_nf_per_km": 0.23}
        self._Htip185_11_kV = {"r_ohm_per_km": 0.164,
                               "x_ohm_per_km": 0.1132,
                               "c_nf_per_km": 0.4,
                               "max_i_ka": 0.295,
                               "r0_ohm_per_km": 0.2477,
                               "x0_ohm_per_km": 0.0485,
                               "c0_nf_per_km": 0.48}
        self._Htip185_22_kV = {"r_ohm_per_km": 0.164,
                               "x_ohm_per_km": 0.1202,
                               "c_nf_per_km": 0.27,
                               "max_i_ka": 0.29,
                               "r0_ohm_per_km": 0.2371,
                               "x0_ohm_per_km": 0.0534,
                               "c0_nf_per_km": 0.245}
        self._Htip240_11_kV = {"r_ohm_per_km": 0.125,
                               "x_ohm_per_km": 0.1084,
                               "c_nf_per_km": 0.46,
                               "max_i_ka": 0.343,
                               "r0_ohm_per_km": 0.2025,
                               "x0_ohm_per_km": 0.0451,
                               "c0_nf_per_km": 0.53}
        self._Htip240_22_kV = {"r_ohm_per_km": 0.125,
                               "x_ohm_per_km": 0.115,
                               "c_nf_per_km": 0.3,
                               "max_i_ka": 0.34,
                               "r0_ohm_per_km": 0.1947,
                               "x0_ohm_per_km": 0.0497,
                               "c0_nf_per_km": 0.27}
        self._Htip240_35_kV = {"r_ohm_per_km": 0.125,
                               "x_ohm_per_km": 0.1242,
                               "c_nf_per_km": 0.23,
                               "max_i_ka": 0.315,
                               "r0_ohm_per_km": 0.1875,
                               "x0_ohm_per_km": 0.0563,
                               "c0_nf_per_km": 0.27}
        self._Htip95_22_kV = {"r_ohm_per_km": 0.32,
                              "x_ohm_per_km": 0.134,
                              "c_nf_per_km": 0.22,
                              "max_i_ka": 0.195,
                              "r0_ohm_per_km": 0.4021,
                              "x0_ohm_per_km": 0.0637,
                              "c0_nf_per_km": 0.19}
        self._HTPO120_11_kV = {"r_ohm_per_km": 0.253,
                               "x_ohm_per_km": 0.1213,
                               "c_nf_per_km": 0.35,
                               "max_i_ka": 0.229,
                               "r0_ohm_per_km": 0.9802,
                               "x0_ohm_per_km": 0.0542,
                               "c0_nf_per_km": 0.58}
        self._HTPO150_11_kV = {"r_ohm_per_km": 0.206,
                               "x_ohm_per_km": 0.1172,
                               "c_nf_per_km": 0.38,
                               "max_i_ka": 0.259,
                               "r0_ohm_per_km": 0.882,
                               "x0_ohm_per_km": 0.0513,
                               "c0_nf_per_km": 0.63}
        self._HTPO150_35_kV = {"r_ohm_per_km": 0.206,
                               "x_ohm_per_km": 0.1345,
                               "c_nf_per_km": 0.19,
                               "max_i_ka": 0.245,
                               "r0_ohm_per_km": 0.7381,
                               "x0_ohm_per_km": 0.0641,
                               "c0_nf_per_km": 0.345}
        self._HTPO185_11_kV = {"r_ohm_per_km": 0.164,
                               "x_ohm_per_km": 0.1132,
                               "c_nf_per_km": 0.4,
                               "max_i_ka": 0.295,
                               "r0_ohm_per_km": 0.8343,
                               "x0_ohm_per_km": 0.0485,
                               "c0_nf_per_km": 0.69}
        self._HTPO185_22_kV = {"r_ohm_per_km": 0.164,
                               "x_ohm_per_km": 0.1202,
                               "c_nf_per_km": 0.27,
                               "max_i_ka": 0.29,
                               "r0_ohm_per_km": 0.7493,
                               "x0_ohm_per_km": 0.0534,
                               "c0_nf_per_km": 0.48}
        self._HTPO240_11_kV = {"r_ohm_per_km": 0.125,
                               "x_ohm_per_km": 0.1084,
                               "c_nf_per_km": 0.46,
                               "max_i_ka": 0.343,
                               "r0_ohm_per_km": 0.7451,
                               "x0_ohm_per_km": 0.0451,
                               "c0_nf_per_km": 0.83}
        self._HTPO240_22_kV = {"r_ohm_per_km": 0.125,
                               "x_ohm_per_km": 0.115,
                               "c_nf_per_km": 0.3,
                               "max_i_ka": 0.34,
                               "r0_ohm_per_km": 0.6831,
                               "x0_ohm_per_km": 0.0497,
                               "c0_nf_per_km": 0.53}
        self._Rezkabel_240_10_kV = {"r_ohm_per_km": 0.0754,
                                    "x_ohm_per_km": 0.1084,
                                    "c_nf_per_km": 0.44,
                                    "max_i_ka": 0.534,
                                    "r0_ohm_per_km": 0.1075,
                                    "x0_ohm_per_km": 0.0451,
                                    "c0_nf_per_km": 0.25}
        self._SZAPKMVB3x120_6per10_kV = {"r_ohm_per_km": 0.253,
                                         "x_ohm_per_km": 0.1213,
                                         "c_nf_per_km": 0.35,
                                         "max_i_ka": 0.225,
                                         "r0_ohm_per_km": 0.3439,
                                         "x0_ohm_per_km": 0.0542,
                                         "c0_nf_per_km": 0.405}
        self._SZAPKMVB3x150_12per20_kV = {"r_ohm_per_km": 0.206,
                                          "x_ohm_per_km": 0.1245,
                                          "c_nf_per_km": 0.25,
                                          "max_i_ka": 0.267,
                                          "r0_ohm_per_km": 0.2815,
                                          "x0_ohm_per_km": 0.0566,
                                          "c0_nf_per_km": 0.139}
        self._SZAPKMVB3x150_6per10_kV = {"r_ohm_per_km": 0.206,
                                         "x_ohm_per_km": 0.1172,
                                         "c_nf_per_km": 0.38,
                                         "max_i_ka": 0.255,
                                         "r0_ohm_per_km": 0.2905,
                                         "x0_ohm_per_km": 0.0513,
                                         "c0_nf_per_km": 0.25}
        self._SZAPKMVB3x185_6per10_kV = {"r_ohm_per_km": 0.164,
                                         "x_ohm_per_km": 0.1132,
                                         "c_nf_per_km": 0.4,
                                         "max_i_ka": 0.29,
                                         "r0_ohm_per_km": 0.2477,
                                         "x0_ohm_per_km": 0.0485,
                                         "c0_nf_per_km": 0.276}
        self._SZAPKMVB3x240_6per10_kV = {"r_ohm_per_km": 0.125,
                                         "x_ohm_per_km": 0.1084,
                                         "c_nf_per_km": 0.46,
                                         "max_i_ka": 0.34,
                                         "r0_ohm_per_km": 0.2025,
                                         "x0_ohm_per_km": 0.0451,
                                         "c0_nf_per_km": 0.3}
        self._SZAQKrKVM3x150_12per20_kV = {"r_ohm_per_km": 0.206,
                                           "x_ohm_per_km": 0.1245,
                                           "c_nf_per_km": 0.25,
                                           "max_i_ka": 0.26,
                                           "r0_ohm_per_km": 0.933,
                                           "x0_ohm_per_km": 0.0566,
                                           "c0_nf_per_km": 0.139}
        self._SZAQKrKVM3x150_6per10_kV = {"r_ohm_per_km": 0.206,
                                          "x_ohm_per_km": 0.1172,
                                          "c_nf_per_km": 0.38,
                                          "max_i_ka": 0.28,
                                          "r0_ohm_per_km": 0.933,
                                          "x0_ohm_per_km": 0.0513,
                                          "c0_nf_per_km": 0.25}
        self._SZAQKrKVM3x185_12per20_kV = {"r_ohm_per_km": 0.164,
                                           "x_ohm_per_km": 0.1202,
                                           "c_nf_per_km": 0.27,
                                           "max_i_ka": 0.29,
                                           "r0_ohm_per_km": 0.891,
                                           "x0_ohm_per_km": 0.0534,
                                           "c0_nf_per_km": 0.153}
        self._SZAQKrKVM3x185_6per10_kV = {"r_ohm_per_km": 0.164,
                                          "x_ohm_per_km": 0.1132,
                                          "c_nf_per_km": 0.4,
                                          "max_i_ka": 0.315,
                                          "r0_ohm_per_km": 0.891,
                                          "x0_ohm_per_km": 0.0485,
                                          "c0_nf_per_km": 0.276}
        self._SZAQKrKVM3x240_12per20_kV = {"r_ohm_per_km": 0.125,
                                           "x_ohm_per_km": 0.115,
                                           "c_nf_per_km": 0.3,
                                           "max_i_ka": 0.34,
                                           "r0_ohm_per_km": 0.852,
                                           "x0_ohm_per_km": 0.0497,
                                           "c0_nf_per_km": 0.167}
        self._SZAQKrKVM3x240_6per10_kV = {"r_ohm_per_km": 0.125,
                                          "x_ohm_per_km": 0.1084,
                                          "c_nf_per_km": 0.46,
                                          "max_i_ka": 0.37,
                                          "r0_ohm_per_km": 0.852,
                                          "x0_ohm_per_km": 0.0451,
                                          "c0_nf_per_km": 0.3}
        self._3x120_AASC_22_kV = {"r_ohm_per_km": 0.287,
                                  "x_ohm_per_km": 0.356,
                                  "c_nf_per_km": 0.011,
                                  "max_i_ka": 0.365,
                                  "r0_ohm_per_km": 0.435,
                                  "x0_ohm_per_km": 1.5693,
                                  "c0_nf_per_km": 0.008}
        self._3x120_AASC_35_kV = {"r_ohm_per_km": 0.287,
                                  "x_ohm_per_km": 0.356,
                                  "c_nf_per_km": 0.009,
                                  "max_i_ka": 0.365,
                                  "r0_ohm_per_km": 0.435,
                                  "x0_ohm_per_km": 1.5693,
                                  "c0_nf_per_km": 0.009}
        self._3x120_ACSR_22_kV = {"r_ohm_per_km": 0.236,
                                  "x_ohm_per_km": 0.356,
                                  "c_nf_per_km": 0.011,
                                  "max_i_ka": 0.41,
                                  "r0_ohm_per_km": 0.384,
                                  "x0_ohm_per_km": 1.5693,
                                  "c0_nf_per_km": 0.008}
        self._3x120_ACSR_35_kV = {"r_ohm_per_km": 0.236,
                                  "x_ohm_per_km": 0.356,
                                  "c_nf_per_km": 0.009,
                                  "max_i_ka": 0.41,
                                  "r0_ohm_per_km": 0.384,
                                  "x0_ohm_per_km": 1.5693,
                                  "c0_nf_per_km": 0.009}
        self._3x120_ASC_22_kV = {"r_ohm_per_km": 0.248,
                                 "x_ohm_per_km": 0.356,
                                 "c_nf_per_km": 0.011,
                                 "max_i_ka": 0.38,
                                 "r0_ohm_per_km": 0.396,
                                 "x0_ohm_per_km": 1.5693,
                                 "c0_nf_per_km": 0.008}
        self._3x150_AASC_11_kV = {"r_ohm_per_km": 0.227,
                                  "x_ohm_per_km": 0.3476,
                                  "c_nf_per_km": 0.011,
                                  "max_i_ka": 0.425,
                                  "r0_ohm_per_km": 0.375,
                                  "x0_ohm_per_km": 1.5609,
                                  "c0_nf_per_km": 0.008}
        self._3x150_AASC_22_kV = {"r_ohm_per_km": 0.227,
                                  "x_ohm_per_km": 0.3476,
                                  "c_nf_per_km": 0.011,
                                  "max_i_ka": 0.425,
                                  "r0_ohm_per_km": 0.375,
                                  "x0_ohm_per_km": 1.5609,
                                  "c0_nf_per_km": 0.008}
        self._3x150_AASC_35_kV = {"r_ohm_per_km": 0.227,
                                  "x_ohm_per_km": 0.3476,
                                  "c_nf_per_km": 0.009,
                                  "max_i_ka": 0.425,
                                  "r0_ohm_per_km": 0.375,
                                  "x0_ohm_per_km": 1.5609,
                                  "c0_nf_per_km": 0.009}
        self._3x150_ACSR_22_kV = {"r_ohm_per_km": 0.195,
                                  "x_ohm_per_km": 0.3476,
                                  "c_nf_per_km": 0.011,
                                  "max_i_ka": 0.47,
                                  "r0_ohm_per_km": 0.343,
                                  "x0_ohm_per_km": 1.5609,
                                  "c0_nf_per_km": 0.008}
        self._3x150_ACSR_35_kV = {"r_ohm_per_km": 0.195,
                                  "x_ohm_per_km": 0.3476,
                                  "c_nf_per_km": 0.009,
                                  "max_i_ka": 0.47,
                                  "r0_ohm_per_km": 0.343,
                                  "x0_ohm_per_km": 1.5609,
                                  "c0_nf_per_km": 0.009}
        self._3x150_ASC_11_kV = {"r_ohm_per_km": 0.196,
                                 "x_ohm_per_km": 0.3476,
                                 "c_nf_per_km": 0.011,
                                 "max_i_ka": 0.44,
                                 "r0_ohm_per_km": 0.344,
                                 "x0_ohm_per_km": 1.5609,
                                 "c0_nf_per_km": 0.008}
        self._3x150_ASC_22_kV = {"r_ohm_per_km": 0.196,
                                 "x_ohm_per_km": 0.3476,
                                 "c_nf_per_km": 0.011,
                                 "max_i_ka": 0.44,
                                 "r0_ohm_per_km": 0.344,
                                 "x0_ohm_per_km": 1.5609,
                                 "c0_nf_per_km": 0.008}
        self._3x150_ASC_35_kV = {"r_ohm_per_km": 0.196,
                                 "x_ohm_per_km": 0.3476,
                                 "c_nf_per_km": 0.009,
                                 "max_i_ka": 0.455,
                                 "r0_ohm_per_km": 0.344,
                                 "x0_ohm_per_km": 1.5609,
                                 "c0_nf_per_km": 0.009}
        self._3x1xNA2XSopeningbracketFclosingbracket2Y95_20per35_kV = {"r_ohm_per_km": 0.32,
                                                                       "x_ohm_per_km": 0.1913,
                                                                       "c_nf_per_km": 0.17,
                                                                       "max_i_ka": 0.256,
                                                                       "r0_ohm_per_km": 0.394,
                                                                       "x0_ohm_per_km": 0.0721,
                                                                       "c0_nf_per_km": 0.295}
        self._3x1xNA2XS2Y240_20per35_kV_RMper25 = {"r_ohm_per_km": 0.125,
                                                   "x_ohm_per_km": 0.1242,
                                                   "c_nf_per_km": 0.23,
                                                   "max_i_ka": 0.426,
                                                   "r0_ohm_per_km": 0.1856,
                                                   "x0_ohm_per_km": 0.0563,
                                                   "c0_nf_per_km": 0.41}
        self._3x1xN2XSopeningbracketFclosingbracket2Y95_12per20_kV_RMper16_Rez = {"r_ohm_per_km": 0.193,
                                                                                  "x_ohm_per_km": 0.134,
                                                                                  "c_nf_per_km": 0.22,
                                                                                  "max_i_ka": 0.321,
                                                                                  "r0_ohm_per_km": 0.2751,
                                                                                  "x0_ohm_per_km": 0.0637,
                                                                                  "c0_nf_per_km": 0.22}
        self._3x1xNA2XSopeningbracketFclosingbracket2Y120_12per20_kV = {"r_ohm_per_km": 0.253,
                                                                        "x_ohm_per_km": 0.1289,
                                                                        "c_nf_per_km": 0.23,
                                                                        "max_i_ka": 0.287,
                                                                        "r0_ohm_per_km": 1.403,
                                                                        "x0_ohm_per_km": 0.0598,
                                                                        "c0_nf_per_km": 0.12}
        self._HME150_22_kV = {"r_ohm_per_km": 0.206,
                              "x_ohm_per_km": 0.1345,
                              "c_nf_per_km": 0.19,
                              "max_i_ka": 0.245,
                              "r0_ohm_per_km": 0.2725,
                              "x0_ohm_per_km": 0.0641,
                              "c0_nf_per_km": 0.445}
        self._SZAPKOVB_3star150_6per10_kV = {"r_ohm_per_km": 0.206,
                                             "x_ohm_per_km": 0.1172,
                                             "c_nf_per_km": 0.54,
                                             "max_i_ka": 0.259,
                                             "r0_ohm_per_km": 0.2905,
                                             "x0_ohm_per_km": 0.0513,
                                             "c0_nf_per_km": 0.25}
        self._SZAPKOVB_3star240_6per10_kV = {"r_ohm_per_km": 0.125,
                                             "x_ohm_per_km": 0.1084,
                                             "c_nf_per_km": 0.67,
                                             "max_i_ka": 0.343,
                                             "r0_ohm_per_km": 0.2025,
                                             "x0_ohm_per_km": 0.0451,
                                             "c0_nf_per_km": 0.3}
        self._3x1xNA2XSopeningbracketFclosingbracket2Y400_6per10_kV = {"r_ohm_per_km": 0.0827,
                                                                       "x_ohm_per_km": 0.0997,
                                                                       "c_nf_per_km": 0.45,
                                                                       "max_i_ka": 0.538,
                                                                       "r0_ohm_per_km": 0.7456,
                                                                       "x0_ohm_per_km": 0.402,
                                                                       "c0_nf_per_km": 0.333}
        self._3x1xNA2XSopeningbracketFclosingbracket2Y400_12per22_kV = {"r_ohm_per_km": 0.0827,
                                                                        "x_ohm_per_km": 0.0997,
                                                                        "c_nf_per_km": 0.45,
                                                                        "max_i_ka": 0.532,
                                                                        "r0_ohm_per_km": 0.7456,
                                                                        "x0_ohm_per_km": 0.402,
                                                                        "c0_nf_per_km": 0.333}
        self._3x1xSZAQAKM_240_12per20_kV = {"r_ohm_per_km": 0.125,
                                            "x_ohm_per_km": 0.458,
                                            "c_nf_per_km": 0.297,
                                            "max_i_ka": 0.391,
                                            "r0_ohm_per_km": 0.852,
                                            "x0_ohm_per_km": 0.0497,
                                            "c0_nf_per_km": 0.167}
        self._3x1xSZAQAKM_240_6per10_kV = {"r_ohm_per_km": 0.125,
                                           "x_ohm_per_km": 0.458,
                                           "c_nf_per_km": 0.297,
                                           "max_i_ka": 0.391,
                                           "r0_ohm_per_km": 0.852,
                                           "x0_ohm_per_km": 0.0497,
                                           "c0_nf_per_km": 0.167}
        self._3x1xSZAQAKM_150_12per20_kV = {"r_ohm_per_km": 0.206,
                                            "x_ohm_per_km": 0.539,
                                            "c_nf_per_km": 0.148,
                                            "max_i_ka": 0.28,
                                            "r0_ohm_per_km": 0.933,
                                            "x0_ohm_per_km": 0.0566,
                                            "c0_nf_per_km": 0.139}
        self._3x1xSZAQAKM_150_6per10_kV = {"r_ohm_per_km": 0.206,
                                           "x_ohm_per_km": 0.481,
                                           "c_nf_per_km": 0.246,
                                           "max_i_ka": 0.283,
                                           "r0_ohm_per_km": 0.933,
                                           "x0_ohm_per_km": 0.0513,
                                           "c0_nf_per_km": 0.25}
        self._3x1xNA2XSopeningbracketFclosingbracket2Y185_12per24_kV = {"r_ohm_per_km": 0.157,
                                                                        "x_ohm_per_km": 0.119,
                                                                        "c_nf_per_km": 0.281,
                                                                        "max_i_ka": 0.361,
                                                                        "r0_ohm_per_km": 0.884,
                                                                        "x0_ohm_per_km": 0.052,
                                                                        "c0_nf_per_km": 0.156}
        self._SZAPKMVB3x185_12per20_kV = {"r_ohm_per_km": 0.164,
                                          "x_ohm_per_km": 0.1132,
                                          "c_nf_per_km": 0.4,
                                          "max_i_ka": 0.29,
                                          "r0_ohm_per_km": 0.2477,
                                          "x0_ohm_per_km": 0.0485,
                                          "c0_nf_per_km": 0.276}
        self._3x1xNA2XSopeningbracketFLclosingbracket2Y120RMper35_40per69_kV = {"r_ohm_per_km": 0.253,
                                                                                "x_ohm_per_km": 0.1289,
                                                                                "c_nf_per_km": 0.23,
                                                                                "max_i_ka": 0.385,
                                                                                "r0_ohm_per_km": 1.403,
                                                                                "x0_ohm_per_km": 0.0598,
                                                                                "c0_nf_per_km": 0.12}
        self._3x1xSZAQRKM_150_6per10_kV = {"r_ohm_per_km": 0.206,
                                           "x_ohm_per_km": 0.418,
                                           "c_nf_per_km": 0.246,
                                           "max_i_ka": 0.283,
                                           "r0_ohm_per_km": 0.933,
                                           "x0_ohm_per_km": 0.0513,
                                           "c0_nf_per_km": 0.25}
        self._3x1xSZAQRKM_240_6per10_kV = {"r_ohm_per_km": 0.125,
                                           "x_ohm_per_km": 0.458,
                                           "c_nf_per_km": 0.297,
                                           "max_i_ka": 0.391,
                                           "r0_ohm_per_km": 0.852,
                                           "x0_ohm_per_km": 0.0497,
                                           "c0_nf_per_km": 0.167}
        self._SZAPKMVB3x240_12per20_kV = {"r_ohm_per_km": 0.125,
                                          "x_ohm_per_km": 0.1084,
                                          "c_nf_per_km": 0.46,
                                          "max_i_ka": 0.34,
                                          "r0_ohm_per_km": 0.2025,
                                          "x0_ohm_per_km": 0.0451,
                                          "c0_nf_per_km": 0.3}
        self._3x1xNA2XSopeningbracketFclosingbracketY240_20per35_kV = {"r_ohm_per_km": 0.125,
                                                                       "x_ohm_per_km": 0.115,
                                                                       "c_nf_per_km": 0.3,
                                                                       "max_i_ka": 0.421,
                                                                       "r0_ohm_per_km": 0.852,
                                                                       "x0_ohm_per_km": 0.0497,
                                                                       "c0_nf_per_km": 0.167}

        self._SZAXKrRKM_3x240_20per35_kV = {"r_ohm_per_km": 0.125,
                                            "x_ohm_per_km": 0.1084,
                                            "c_nf_per_km": 0.46,
                                            "max_i_ka": 0.34,
                                            "r0_ohm_per_km": 0.2025,
                                            "x0_ohm_per_km": 0.0451,
                                            "c0_nf_per_km": 0.3}
        self._SZAPhKeOVB_3x120_12per20_kV = {"r_ohm_per_km": 0.125,
                                             "x_ohm_per_km": 0.1084,
                                             "c_nf_per_km": 0.46,
                                             "max_i_ka": 0.34,
                                             "r0_ohm_per_km": 0.2025,
                                             "x0_ohm_per_km": 0.0451,
                                             "c0_nf_per_km": 0.3}
        self._SZAPhKeOVB_3x185_12per20_kV = {"r_ohm_per_km": 0.125,
                                             "x_ohm_per_km": 0.1084,
                                             "c_nf_per_km": 0.46,
                                             "max_i_ka": 0.34,
                                             "r0_ohm_per_km": 0.2025,
                                             "x0_ohm_per_km": 0.0451,
                                             "c0_nf_per_km": 0.3}
